// initialize mongodb connection
const path = require('path');
const { exit } = require('process');
console.debug(path.resolve(__dirname, "config/.env"))
require('dotenv').config({ path: path.resolve(__dirname, "..", "config/.env") });
require("../connectDatabase")();

const seederPath = path.resolve(__dirname, "..", "seeders");

Promise.all([
  require(`${seederPath}/adminSeed.js`).seed(),
  require(`${seederPath}/userSeed.js`).seed(),
  require(`${seederPath}/showSeed.js`).seed(),
  require(`${seederPath}/actorSeed.js`).seed(),
]).then(() => {
  // seeds that are dependent on contents
  // generated by above seeders
  Promise.all([
    require(`${seederPath}/showReviewSeed.js`).seed(),
    require(`${seederPath}/actorReviewSeed.js`).seed(),
    require(`${seederPath}/filmographySeed.js`).seed()
  ]).then(() => {
    exit();
  })

});




