/* args must be file names inside /server/src/seeders directory */
let argv = process.argv.slice(2);
const fs = require('fs');
// initialize mongodb connection
const path = require('path');
const { exit } = require('process');
console.debug(path.resolve(__dirname, "config/.env"))
require('dotenv').config({ path: path.resolve(__dirname, "..", "config/.env") });
require("../connectDatabase")();

const seederPath = path.resolve(__dirname, "..", "seeders");

const seeder = async () => {

  if (argv.length <= 0) {
    console.log('seeding database');
    await Promise.all([
      require(`${seederPath}/adminSeed.js`).seed(),
      require(`${seederPath}/userSeed.js`).seed(),
      require(`${seederPath}/showSeed.js`).seed(),
      require(`${seederPath}/actorSeed.js`).seed(),
    ]).then(() => {
      // seeds that are dependent on contents
      // generated by above seeders
      return Promise.all([
        require(`${seederPath}/showReviewSeed.js`).seed(),
        require(`${seederPath}/actorReviewSeed.js`).seed(),
        require(`${seederPath}/filmographySeed.js`).seed()
      ])
    });

  } else {
    // remove non-existent files first 
    argv = argv.filter(arg => fs.existsSync(`${seederPath}/${arg}`))
    console.log('calling seeders', [...argv])
    await Promise.all(argv.map(arg => require(
      `${seederPath}/${arg}`
    ).seed()
    ));
  }
  return;
};

seeder().then(() => exit());





